using UnrealSharp.Attributes;
using UnrealSharp.Core.Attributes;
using UnrealSharp.Interop;
using UnrealSharp.Core.Marshallers;

namespace UnrealSharp.UnrealSharpEditor;

[UClass, GeneratedType("CSUnrealSharpEditorSettings", "UnrealSharp.UnrealSharpEditor.CSUnrealSharpEditorSettings")]
public partial class UCSUnrealSharpEditorSettings : UnrealSharp.DeveloperSettings.UDeveloperSettings
{
    static readonly IntPtr NativeClassPtr;
    static UCSUnrealSharpEditorSettings()
    {
        NativeClassPtr = UCoreUObjectExporter.CallGetNativeClassFromName(typeof(UCSUnrealSharpEditorSettings).GetAssemblyName(), "UnrealSharp.UnrealSharpEditor", "CSUnrealSharpEditorSettings");
        IntPtr AutomaticHotReloading_NativeProperty = FPropertyExporter.CallGetNativePropertyFromName(NativeClassPtr, "AutomaticHotReloading");
        AutomaticHotReloading_Offset = FPropertyExporter.CallGetPropertyOffset(AutomaticHotReloading_NativeProperty);
        IntPtr BuildConfiguration_NativeProperty = FPropertyExporter.CallGetNativePropertyFromName(NativeClassPtr, "BuildConfiguration");
        BuildConfiguration_Offset = FPropertyExporter.CallGetPropertyOffset(BuildConfiguration_NativeProperty);
        IntPtr LogVerbosity_NativeProperty = FPropertyExporter.CallGetNativePropertyFromName(NativeClassPtr, "LogVerbosity");
        LogVerbosity_Offset = FPropertyExporter.CallGetPropertyOffset(LogVerbosity_NativeProperty);
        IntPtr bSuffixGeneratedTypes_NativeProperty = FPropertyExporter.CallGetNativePropertyFromName(NativeClassPtr, "bSuffixGeneratedTypes");
        bSuffixGeneratedTypes_Offset = FPropertyExporter.CallGetPropertyOffset(bSuffixGeneratedTypes_NativeProperty);
    }
    
    static int AutomaticHotReloading_Offset;
    
    /// <summary>
    /// Whether Hot Reload should automatically start on script save, gaining Editor focus, or not at all.
    /// </summary>
    public UnrealSharp.UnrealSharpEditor.EAutomaticHotReloadMethod AutomaticHotReloading
    {
        get
        {
            return EnumMarshaller<UnrealSharp.UnrealSharpEditor.EAutomaticHotReloadMethod>.FromNative(IntPtr.Add(NativeObject, AutomaticHotReloading_Offset), 0);
        }
        init
        {
            EnumMarshaller<UnrealSharp.UnrealSharpEditor.EAutomaticHotReloadMethod>.ToNative(IntPtr.Add(NativeObject, AutomaticHotReloading_Offset), 0, value);
        }
    }
    
    
    static int BuildConfiguration_Offset;
    
    /// <summary>
    /// The build configuration to use when building the C# project in the editor.
    /// </summary>
    public UnrealSharp.UnrealSharpEditor.ECSBuildConfiguration BuildConfiguration
    {
        get
        {
            return EnumMarshaller<UnrealSharp.UnrealSharpEditor.ECSBuildConfiguration>.FromNative(IntPtr.Add(NativeObject, BuildConfiguration_Offset), 0);
        }
        init
        {
            EnumMarshaller<UnrealSharp.UnrealSharpEditor.ECSBuildConfiguration>.ToNative(IntPtr.Add(NativeObject, BuildConfiguration_Offset), 0, value);
        }
    }
    
    
    static int LogVerbosity_Offset;
    
    /// <summary>
    /// The verbosity level of the logs generated by MSBuild when building the C# project in the editor.
    /// </summary>
    public UnrealSharp.UnrealSharpEditor.ECSLoggerVerbosity LogVerbosity
    {
        get
        {
            return EnumMarshaller<UnrealSharp.UnrealSharpEditor.ECSLoggerVerbosity>.FromNative(IntPtr.Add(NativeObject, LogVerbosity_Offset), 0);
        }
        init
        {
            EnumMarshaller<UnrealSharp.UnrealSharpEditor.ECSLoggerVerbosity>.ToNative(IntPtr.Add(NativeObject, LogVerbosity_Offset), 0, value);
        }
    }
    
    
    static int bSuffixGeneratedTypes_Offset;
    
    /// <summary>
    /// Should we suffix generated types' DisplayName with "TypeName (C#)"?
    /// Needs restart to take effect.
    /// </summary>
    public bool SuffixGeneratedTypes
    {
        get
        {
            return BoolMarshaller.FromNative(IntPtr.Add(NativeObject, bSuffixGeneratedTypes_Offset), 0);
        }
        init
        {
            BoolMarshaller.ToNative(IntPtr.Add(NativeObject, bSuffixGeneratedTypes_Offset), 0, value);
        }
    }
    
    
}